### ISSUE TITLE
getChannels() doesn't list Forum Channels

### ISSUE THREAD

**Issue by Renaud-Dov** [discord-jda/JDA#2476]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I should have `test` and `test-prod`forum channels listed, but I can't find them.
![image](https://github.com/discord-jda/JDA/assets/14821642/52101a5e-3cfb-4e38-8abc-f5173863ca8d)
<img width="243" alt="image" src="https://github.com/discord-jda/JDA/assets/14821642/fb6511ce-10f7-4462-8d35-6c422dbf68b4">

### Code Example for Reproduction Steps

```java
event.getGuild().getChannels()
// or what I want to use: 
thread.getParentChannel(); // return null
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
var botAdapter = new BotAdapter(discordService, requestService);
        var builder = JDABuilder.createDefault(token);
        builder.enableIntents(GatewayIntent.GUILD_MESSAGES, GatewayIntent.DIRECT_MESSAGES, GatewayIntent.GUILD_MEMBERS);
        builder.disableCache(CacheFlag.MEMBER_OVERRIDES, CacheFlag.VOICE_STATE);
        builder.setBulkDeleteSplittingEnabled(false);
        builder.addEventListeners(botAdapter);
        DiscordService.setInstance(builder.build());

        DiscordService.botInstance.updateCommands().addCommands( ... ).queue();
```

**Comment by MinnDevelopment** [comment]
Those `toString()` outputs indicate that you are not using the latest version. We are currently on `5.0.0-beta.10`. I would recommend updating to that version. Note that forum channels are only supported on JDA v5, if you are using v4 you cannot interact with threads in general which includes forums.

**Comment by Renaud-Dov** [comment]
I do use the latest version:
```xml
<dependency>
    <groupId>net.dv8tion</groupId>
    <artifactId>JDA</artifactId>
    <version>5.0.0-alpha.10</version>
</dependency>
```

**Comment by Xirado** [comment]
`5.0.0-alpha.10` is not latest. `5.0.0-beta.10` is.

**Comment by Renaud-Dov** [comment]
🤦
My bad, I really need glasses ^^
Thanks for the help 👍
