### ISSUE TITLE
Mavencentral does not contain version beta.11

### ISSUE THREAD

**Issue by DxsSucuk** [discord-jda/JDA#2481]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

N/A

### Code Example for Reproduction Steps

```java
<dependency>
   <groupId>net.dv8tion</groupId>
   <artifactId>JDA</artifactId>
   <version>5.0.0-beta.11</version>
</dependency>
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
N/A
```

### Exception or Error

```yesyes
N/A
```

**Comment by Andre601** [comment]
Pretty sure it can take a while before latest release is published on maven central.

**Comment by DxsSucuk** [comment]
From my experience it takes about max 1 hour finish up and be ready? And right now it almost takes 2 hours?
