### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: kotlin.Unit

### ISSUE THREAD

**Issue by AmirAli-AZ** [discord-jda/JDA#2497]
### General Troubleshooting

- [x] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

Hi i just created a java project and added latest jda dependency
but when i run project i get  an error

### Code Example for Reproduction Steps

```java
N/A
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
if (args.length < 1) {
    System.out.println("Provide the token");
    System.exit(1);
}

var jda = JDABuilder.createDefault(args[0])
              .setActivity(Activity.playing("JavaFX"))
              .addEventListeners(
                  new GeneralListener()
               )
               .build();

jda.updateCommands().addCommands(
    Commands.slash("ping", "get ping of the bot")
).queue();
```

### Exception or Error

```yesyes
> Task :Main.main() FAILED
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/Unit
	at okhttp3@4.10.0/okhttp3.Dispatcher.setMaxRequestsPerHost(Dispatcher.kt:70)
	at net.dv8tion.jda@5.0.0-beta.12/net.dv8tion.jda.internal.utils.IOUtil.newHttpClientBuilder(IOUtil.java:107)
	at net.dv8tion.jda@5.0.0-beta.12/net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1787)
	at org.pw.bot/org.pw.bot.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: kotlin.Unit
Caused by: java.lang.ClassNotFoundException: kotlin.Unit
```

**Comment by MinnDevelopment** [comment]
This is a problem with the way you build your project:

[NoClassDefFoundError or ClassNotFoundException on startup](https://jda.wiki/using-jda/troubleshooting/#noclassdeffounderror-or-classnotfoundexception-on-startup)

I recommend following the [setup guide](https://jda.wiki/setup/intellij/) and adding a [logging framework](https://jda.wiki/setup/logging/).
