### ISSUE TITLE
how can i get the message from discord was marked as "only you can see"

### ISSUE THREAD

**Issue by hua060097** [discord-jda/JDA#2502]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

how can i get the message from discord was marked as "only you can see" in eventlistener

### Code Example for Reproduction Steps

```java
.addEventListeners(new MessageListener())
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
in MessageListener
```

**Comment by Andre601** [comment]
Fairly sure you can't as bots won't receive such messages. They only send them.

And if this is about automated user accounts, be adviced that JDA no longer supports nor encourages automated user accounts as those are a violation of Discord's ToS.

**Comment by MinnDevelopment** [comment]
These are called [ephemeral messages](https://jda.wiki/using-jda/interactions/#ephemeral-messages) and can only be used as a reply to interactions. Bots do not receive ephemeral messages from other bots, as you can imagine, only the user can see them.
