### ISSUE TITLE
Message#getCategory()

### ISSUE THREAD

**Issue by AlexCai2019** [discord-jda/JDA#2509]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

`Message#getCategory()` calls `Message#getGuildChannel()` while getGuildChannel() throws an exception when the message isn't from a guild, but the docs states that getCategory() should return null.
[Document of Message#getCategory()](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/Message.html#getCategory())
![image](https://github.com/discord-jda/JDA/assets/89138532/e4887081-5aaf-4530-bc36-6a7b8d509b2e)
[Source code of Message#getCategory()](https://github.com/discord-jda/JDA/blob/v5.0.0-beta.12/src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java#L459)
[Source code of Message#getGuildChannel()](https://github.com/discord-jda/JDA/blob/v5.0.0-beta.12/src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java#L451)

### Code Example for Reproduction Steps

```java
public class MessageEvent extends ListenerAdapter
{
	@Override
	public void onMessageReceived(MessageReceivedEvent event)
	{
		event.getMessage().getCategory();
	}
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDA jda = JDABuilder.createDefault(args[0]).addEventListeners(new MessageEvent()).enableIntents(GatewayIntent.MESSAGE_CONTENT).build();
```

### Exception or Error

```yesyes
java.lang.IllegalStateException
```

**Comment by MinnDevelopment** [comment]
Fixed in [5.0.0-beta.13](https://github.com/discord-jda/JDA/releases/tag/v5.0.0-beta.13)
