### ISSUE TITLE
When I disable a Actionrow with buttons only disable first button

### ISSUE THREAD

**Issue by gabrizete** [discord-jda/JDA#2547]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I have two buttons on a embed messge and when I click on first button disables only first button and when I click on second button disables both. The  expected behavior is disable both button no matter what button you click.

### Code Example for Reproduction Steps

```java
@Override
    public void onButtonInteraction(ButtonInteractionEvent event) {
        ...
        event.editComponents(ActionRow.of(
                Button.of(ButtonStyle.SUCCESS, "authenticator_accepted", "Accept").asDisabled(),
                Button.of(ButtonStyle.DANGER, "authenticator_its_not_me", "It's not me!").asDisabled()
        )).queue();
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder.createLight(ENV.get("TOKEN"),
                GatewayIntent.MESSAGE_CONTENT,
                GatewayIntent.GUILD_PRESENCES,
                GatewayIntent.GUILD_MEMBERS)
                .setStatus(OnlineStatus.ONLINE)
                .addEventListeners(new InteractionExecutor(commandExecutors, modalExecutors))
                .addEventListeners(requestPlayerForAuthentication)
                .build().awaitReady();
```

**Comment by MinnDevelopment** [comment]
I cannot reproduce any issue with your provided code sample. Can you provide a minimally reproducible example?

**Comment by gabrizete** [comment]
I will create a repository with the project without the database and redis to make it easier and I will send the link here. Thank you for your attention!

**Comment by gabrizete** [comment]
Sorry, trying to reproduce the problem discovered my error. basically the event had already been sent a response but I managed to do it in a way that didn't trigger an exception (I don't know how I did that) it only triggered the exception when I clicked on the undisabled button again so I thought it was a bug. Sorry again and thanks for your attention.
