### ISSUE TITLE
GuildVoiceUpdateEvent is executed twice

### ISSUE THREAD

**Issue by Limon4ikXDorORIG** [discord-jda/JDA#2568]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.0.0-beta.15

### Expected Behaviour

On join to voice channel:
GuildVoiceUpdateEvent[audio-channel](null -> VoiceChannel:𝐕𝐎𝐈𝐂𝐄-𝐂𝐇𝐀𝐍𝐍𝐄𝐋𝟏(id=1160903440910794792))

On leave from voice channel:
GuildVoiceUpdateEvent[audio-channel](VoiceChannel:𝐕𝐎𝐈𝐂𝐄-𝐂𝐇𝐀𝐍𝐍𝐄𝐋𝟏(id=1160903440910794792) -> null)

### Code Example for Reproduction Steps

```java
public class Listenr extends ListenerAdapter{
    @Override
    public void onGuildVoiceUpdate(@NotNull GuildVoiceUpdateEvent event){
        System.out.println(event);
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDA jda = JDABuilder.createDefault("token").build();
```

### Exception or Error

```yesyes
On join to voice channel:
GuildVoiceUpdateEvent[audio-channel](null -> VoiceChannel:𝐕𝐎𝐈𝐂𝐄-𝐂𝐇𝐀𝐍𝐍𝐄𝐋𝟏(id=1160903440910794792))
GuildVoiceUpdateEvent[audio-channel](null -> VoiceChannel:𝐕𝐎𝐈𝐂𝐄-𝐂𝐇𝐀𝐍𝐍𝐄𝐋𝟏(id=1160903440910794792))

On leave from voice channel:
GuildVoiceUpdateEvent[audio-channel](VoiceChannel:𝐕𝐎𝐈𝐂𝐄-𝐂𝐇𝐀𝐍𝐍𝐄𝐋𝟏(id=1160903440910794792) -> null)
GuildVoiceUpdateEvent[audio-channel](VoiceChannel:𝐕𝐎𝐈𝐂𝐄-𝐂𝐇𝐀𝐍𝐍𝐄𝐋𝟏(id=1160903440910794792) -> null)
```

**Comment by freya022** [comment]
I really doubt that your `JDABuilder` is like this, because if it was, your listener would not work at all, please post your entire `JDABuilder` when asked

**Comment by Limon4ikXDorORIG** [comment]
//JDA BUILD START\\
        JDA jda = JDABuilder.createDefault(this.token)            .enableIntents(gatewayIntents) // ОТКРЫВАЕМ ШЛЮЗЫ
            .setMemberCachePolicy(MemberCachePolicy.ALL) // ВЫБИРАЕМ КЕШИРОВАНИЕ            .setChunkingFilter(ChunkingFilter.ALL) // И ТУТ ТОЖЕ
            .setActivity(Activity.watching(this.activiti)) // АКТИВНОСТЬ            .build(); // НЕ ТРУДНО ДОГОДАТЬСЯ
        //JDA BUILD   END\\
        //START ADDING COMMANDS\\
        CommandManager commandManager = new CommandManager();
        commandManager.add(new SendRules());        commandManager.add(new SendRegisterMessage());
        commandManager.add(new Coin());        commandManager.add(new Ping());
        commandManager.add(new Avatar());        commandManager.add(new countMessages());
        //END   ADDING COMMANDS\\
        //START ADDING LISTENERS\\
        jda.addEventListener(commandManager);        jda.addEventListener(new PlayerListeners());
        jda.addEventListener(new ButtonListeners());        jda.addEventListener(new StatisticListener());
        jda.addEventListener(new StatisticListener());
        //END   ADDING LISTENERS\\

**Comment by Limon4ikXDorORIG** [comment]
//JDA BUILD START\\
        JDA jda = JDABuilder.createDefault(this.token)            .enableIntents(gatewayIntents) // ОТКРЫВАЕМ ШЛЮЗЫ
            .setMemberCachePolicy(MemberCachePolicy.ALL) // ВЫБИРАЕМ КЕШИРОВАНИЕ            .setChunkingFilter(ChunkingFilter.ALL) // И ТУТ ТОЖЕ
            .setActivity(Activity.watching(this.activiti)) // АКТИВНОСТЬ            .build(); // НЕ ТРУДНО ДОГОДАТЬСЯ
        //JDA BUILD   END\\
        //START ADDING COMMANDS\\
        CommandManager commandManager = new CommandManager();
        commandManager.add(new SendRules());        commandManager.add(new SendRegisterMessage());
        commandManager.add(new Coin());        commandManager.add(new Ping());
        commandManager.add(new Avatar());        commandManager.add(new countMessages());
        //END   ADDING COMMANDS\\
        //START ADDING LISTENERS\\
        jda.addEventListener(commandManager);        jda.addEventListener(new PlayerListeners());
        jda.addEventListener(new ButtonListeners());        jda.addEventListener(new StatisticListener());
        jda.addEventListener(new StatisticListener());
        //END   ADDING LISTENERS\\

**Comment by Limon4ikXDorORIG** [comment]
> Я не могу воспроизвести, но я предполагаю, что вы просто дважды зарегистрировали прослушиватель.

Thanks for the answer, it helped me.
