### ISSUE TITLE
First slash command registered does not register

### ISSUE THREAD

**Issue by ItsCre3per** [discord-jda/JDA#2579]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.0.0-beta.12

### Expected Behaviour

Expected Behavior: 
When I register guild slash commands with `upsertCommand()` and update the bot's commands with `updateCommands()`, all 
commands registered should appear on my bot's tab when I type the `/` key. 

Actual Behavior: 
When I register guild slash commands with `upsertCommand()` and update the bot's commands with `updateCommands()`, all 
commands registered EXCEPT for the first one appear on my bot's tab when I type the `/` key. 

Reference: 
When I say "my bot's tab" I mean the area where my bot's slash commands are in Discord when a user types the `/` key and the options pop up.

### Code Example for Reproduction Steps

```java
public class CreeperBot extends ListenerAdapter {
    public static void main(String[] args) throws InterruptedException {
        // Build the bot with necessary gateways (permissions), the token, set the bot's activity, and implement the listeners in other classes
        JDA jda = JDABuilder.createDefault("token",
                        GatewayIntent.GUILD_MESSAGES, GatewayIntent.MESSAGE_CONTENT, GatewayIntent.GUILD_MEMBERS,
                        GatewayIntent.GUILD_VOICE_STATES, GatewayIntent.GUILD_EMOJIS_AND_STICKERS, GatewayIntent.SCHEDULED_EVENTS)
                .setActivity(Activity.watching("Creeper's Server")).addEventListeners(new GameCommands()).build().awaitReady();
        // Get the Bot Test server ID and check if null
        Guild guild = jda.getGuildById("server id here");
        if(guild != null) {
            // Register slash commands in other classes
            // To register commands globally, use the jda variable directly, not the guild variable
            guild.upsertCommand("test", "a test command.").queue();
            guild.upsertCommand("bal", "check your balance").queue();
            guild.upsertCommand("setbal", "set your balance")
                    .addOption(OptionType.INTEGER, "num", "The value to set", true).queue();
            guild.updateCommands().queue();

        }
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
// This code is also pasted in Code Example for Reproduction Steps above.
JDA jda = JDABuilder.createDefault("token",
                        GatewayIntent.GUILD_MESSAGES, GatewayIntent.MESSAGE_CONTENT, GatewayIntent.GUILD_MEMBERS,
                        GatewayIntent.GUILD_VOICE_STATES, GatewayIntent.GUILD_EMOJIS_AND_STICKERS, GatewayIntent.SCHEDULED_EVENTS)
                .setActivity(Activity.watching("Creeper's Server")).addEventListeners(new GameCommands()).build().awaitReady();
```

### Exception or Error

```yesyes
N/A
```

**Comment by MinnDevelopment** [comment]
This is correct behavior, please read the documentation for updateCommands (which replaces all your commands with an empty list here) and follow the example code given in [SlashBotExample](https://github.com/discord-jda/JDA/blob/master/src/examples/java/SlashBotExample.java).

**Comment by ItsCre3per** [comment]
I see, using the method in the link you gave me worked fine, thank you!
