### ISSUE TITLE
Add TextInputInteractionEvent

### ISSUE THREAD

**Issue by goteusz-maszyk** [discord-jda/JDA#2598]
### General Troubleshooting

- [x] I have updated to the [latest JDA version](https://github.com/discord-jda/JDA/releases/latest)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.
- [X] I have checked for similar issues on the Issue-tracker.

### Feature Request

There are already text inputs in JDA, but they're ONLY available for modals. However, discord also supports them as message components and they can be _sent_ as action row:
`addComponents(ActionRow.of(TextInput.create("id", "label", TextInputStyle.SHORT).build()))`

However, there's no way to receive it once it's filled in by user.

### Example Use-Case

```java
// basically anything what's about more interactive commands & messages :)
```

**Comment by MinnDevelopment** [comment]
From what I can tell, they cannot be sent in messages:

Error from JDA if you try to send it:

```
java.lang.IllegalArgumentException: Provided component layout is invalid for messages!
	at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:62)
	at net.dv8tion.jda.api.utils.messages.MessageCreateBuilder.addComponents(MessageCreateBuilder.java:166)
```

Error from discord if you do it without JDA:

```
net.dv8tion.jda.api.exceptions.ErrorResponseException: 50035: Invalid Form Body
data.components[0].components[0]
	- UNION_TYPE_CHOICES: Value of field "type" must be one of (2, 3, 5, 6, 7, 8).
```

What makes you think this is possible?

**Comment by goteusz-maszyk** [comment]
https://discord.com/developers/docs/interactions/message-components#message-components

**Comment by Xirado** [comment]
The discord docs here are misleading, you can use all of them in messages, but not text inputs.

**Comment by goteusz-maszyk** [comment]
oh, ok then.
