### ISSUE TITLE
Voice connect return RestAction

### ISSUE THREAD

**Issue by zvyap** [discord-jda/JDA#2606]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://github.com/discord-jda/JDA/releases/latest)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Currently AudioManager#openAudioConnection and DirectAudioController#connect both are void method
It also queue to connect to the voice channel, why not using RestAction

### Example Use-Case

```java
jda.getDirectAudioController().connect(audioChannel).queue();
```

**Comment by freya022** [comment]
The connection is done through the web socket, it is not a REST action

What would be the use case for having a callback here?

You should also be using the `AudioManager` instead

**Comment by zvyap** [comment]
> You should also be using the `AudioManager` instead

Im using a custom service (another application) to handle my voice connection, so DirectAudioController#connect is doing a REST API call to my audio service.

> What would be the use case for having a callback here?

After invoking the DirectAudioController#connect or AudioManager#openAudioConnection method, I am unable to determine whether the connection has been successfully established. When I attempt to start a music track immediately after the connection request, there are occasions where the music begins to play before the voice connection is fully established.

![image](https://github.com/discord-jda/JDA/assets/52874570/431e1231-956d-4973-93d7-96df74dd8d85)
Although player#queue also makes a REST API call to my custom service, it actually calls first, before DirectAudioController#connect finished the REST API call.

It would be beneficial if DirectAudioController#connect or AudioManager#openAudioConnection returned a RestAction.

It also makes sense for these methods to return a RestAction, considering that most actions communicating with the Discord API utilize RestAction.

**Comment by freya022** [comment]
I'm not sure how your `DirectAudioController#connect` is doing a REST action, JDA's implementation doesn't as far as I can tell.

I haven't found how to set a different implementation either, but even if your implementation did a REST action, JDA doesn't, so it doesn't make sense to return a `RestAction`.

Most actions communication with Discord are indeed REST actions, so `RestAction` is returned.

I haven't messed with audio at all, but if you really want to wait for the connection to be completed, there may be an event for it, not sure though, that seems complicated for a little bit of missed audio

**Comment by zvyap** [comment]
> I'm not sure how your `DirectAudioController#connect` is doing a REST action, JDA's implementation doesn't as far as I can tell.
> 
> I haven't found how to set a different implementation either, but even if your implementation did a REST action, JDA doesn't, so it doesn't make sense to return a `RestAction`.
> 
> Most actions communication with Discord are indeed REST actions, so `RestAction` is returned.
> 

Im using VoiceDispatchInterceptor which VoiceDispatchInterceptor#onVoiceServerUpdate to get the voice connection token, endpoint, and session ID.

It seems that JDA did submit a call to the Discord API to obtain those data to establish a connection to the voice channel.

> I haven't messed with audio at all, but if you really want to wait for the connection to be completed, there may be an event for it, not sure though, that seems complicated for a little bit of missed audio

I will try my best, but still hope for RestAction implementation for voice connection

**Comment by MinnDevelopment** [comment]
This request is not a REST request, it sends a one-way request through the gateway and does not get a reply like a RestAction would. The "reply" is the voice server update event, which cannot be directly tied to the original request, which is why a callback for this is not possible.

Your server should simply not start playing until the voice websocket is established in its entirety. How that happens depends on your custom implementation, not JDA. JDA has no clue about your voice connection, it only sends your request to start the connect. The connect request itself really only gets you the endpoint to connect the voice websocket, which then does the rest.

**Comment by zvyap** [comment]
> This request is not a REST request, it sends a one-way request through the gateway and does not get a reply like a RestAction would. 

Oh, sorry. I knew this from the beginning, but I overlooked the fact that the place where RestAction is returned is the actual REST API call, not one of those one-way requests.

> JDA has no clue about your voice connection, it only sends your request to start the connect.

Yes. I know that. For cartify, I just want to know when is the "request to start the connection" has been done. It also a call to Discord API, should be returned RestAction or CompletableFuture, this is what I asked.

> The "reply" is the voice server update event, which cannot be directly tied to the original request, which is why a callback for this is not possible.

Although I don't think it is not possible, but as you said this, I will just admit this is the case.
(The reqeust still returned guild_id, so it is possible to return CompletableFuture at some point)

Thanks a lot for the reply, I will find another solution for this.

**Comment by MinnDevelopment** [comment]
> The reqeust still returned guild_id, so it is possible to return CompletableFuture at some point

Since the request is idempotent, you only get a reply on the very first request you send. If you send multiple connect/reconnect/disconnect requests there is no way to tell what tiggered which event.

**Comment by zvyap** [comment]
> > The reqeust still returned guild_id, so it is possible to return CompletableFuture at some point
> 
> Since the request is idempotent, you only get a reply on the very first request you send. If you send multiple connect/reconnect/disconnect requests there is no way to tell what tiggered which event.

Ya... I see the problem here. It is not possible to return a callback to the caller.
Thanks for the help!
