### ISSUE TITLE
Button#getLabel() is marked as @Nonnull, but is an optional field in API documentation

### ISSUE THREAD

**Issue by LatvianModder** [discord-jda/JDA#2608]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.0.0-beta.19

### Expected Behaviour

Change Nonnull to Nullable

### Code Example for Reproduction Steps

```java
.
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
.
```

**Comment by LatvianModder** [comment]
Button has to have either label or emoji, but both fields are optional. Label-less button example:
![](https://i.latvian.dev/pc/2024-01-19_19.46.32.png)

**Comment by kazuryyx** [comment]
Have you checked if the method throws?
If not I'll make a PR about this shortly.

**Comment by MinnDevelopment** [comment]
It cannot be null in jda.
