### ISSUE TITLE
First GuildMemberRoleAddEvent or GuildMemberRoleRemoveEvent does not fire

### ISSUE THREAD

**Issue by RedPanda4552** [discord-jda/JDA#2613]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.0.0-beta.20

### Expected Behaviour

All role add/remove actions in a server should fire their respective GuildMemberRoleAddEvent or GuildMemberRoleRemoveEvent events.

After starting up the bot, the very first add/remove action taken by a user in a server does not fire. Any subsequent events fire without issue. No difference whether it is an add or a remove, if two adds are done in a row, two deletes in a row, a mixture of both, etc. All combinations net the same outcome where the very first event does not fire, and all subsequent events do.

### Code Example for Reproduction Steps

```java
public class RoleEventListener extends ListenerAdapter {

    @Override
    public void onGuildMemberRoleAdd(GuildMemberRoleAddEvent event) {
        System.out.println("Put a breakpoint here");
    }

    @Override
    public void onGuildMemberRoleRemove(GuildMemberRoleRemoveEvent event) {
        System.out.println("Put a breakpoint here");
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
jda = JDABuilder.createDefault(discordBotToken)
        .enableIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntent.MESSAGE_CONTENT)
        .setMemberCachePolicy(MemberCachePolicy.ALL)
        .setAutoReconnect(true)
        .build().awaitReady();
```

### Exception or Error

```yesyes
N/A
```

**Comment by Andre601** [comment]
By the looks of it did you not add the RoleEventListener class to your JDABuilder as a new event listener.

**Comment by RedPanda4552** [comment]
I don't include my event listeners in the initial method chain off of the constructor. I register them individually later.

Message events seem to work just fine, these events are the only ones which seem to exhibit this behavior. Should I register them in the method chain instead?

**Comment by Andre601** [comment]
Well, a first step would be to share where and how you register them.

**Comment by RedPanda4552** [comment]
I register them shortly after I read in some config files, to prevent a race between an event firing and my config data not yet being present to guide how those events are handled:

```java
jda.addEventListener(roleEventListener = new RoleEventListener());
jda.addEventListener(messageEventListener = new MessageEventListener());
jda.addEventListener(memberEventListener = new MemberEventListener());
jda.addEventListener(slashCommandListener = new SlashCommandListener());
jda.addEventListener(messageCommandListener = new MessageContextCommandListener());
```

It is worth noting I am waiting until after this entire initialization process has finished before testing this behavior (my bot changes its presence status to indicate this entire init sequence has completed, plus I can see it clearly in the debug console).

I took care of the privileged gateway intents a long time ago for both my production and debug bot applications, else many features would stop working entirely:
![image](https://github.com/discord-jda/JDA/assets/6377490/815e8b01-2048-4f9c-b136-88362f4c8612)

**Comment by MinnDevelopment** [comment]
This event only fires once a member has been loaded into cache. Just because you set the cache policy to `ALL` does not mean the member is cached right away, it is only cached once JDA sees any activity from them.

You can use [GuildMemberUpdateEvent](https://docs.jda.wiki/net/dv8tion/jda/api/events/guild/member/GuildMemberUpdateEvent.html) if you want to avoid relying on cache. Otherwise you have to explicitly load all members on startup into cache, using [chunking filter](https://docs.jda.wiki/net/dv8tion/jda/api/JDABuilder.html#setChunkingFilter(net.dv8tion.jda.api.utils.ChunkingFilter)).
