### ISSUE TITLE
event.getTarget().getMember() returns null in onMessageContextInteraction

### ISSUE THREAD

**Issue by AveCard1nal** [discord-jda/JDA#2615]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.0.0-beta.20

### Expected Behaviour

Hello.
Encountered an error in the onMessageContextInteraction event.
When attempting to retrieve the author of the message (event.getTarget().getMember()), it returns null (called for a message in the Guild).
However, the method works correctly if the author of the message is the same user that triggers the onMessageContextInteraction event.

### Code Example for Reproduction Steps

```java
@Override
    public void onMessageContextInteraction(MessageContextInteractionEvent event) {
        System.out.println(event.getTarget().getMember()); //null
    }
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
this.jda = JDABuilder.createDefault(BOT_TOKEN).enableIntents(GatewayIntent.GUILD_MEMBERS).build();
```

**Comment by freya022** [comment]
On messages from context message commands, `Message#getMember` is not null if the member is cached.

You can either enable the cache with `MemberCachePolicy` and `ChunkingFilter`, or, retrieve the member with `Guild#retrieveMember` and passing `Message#getAuthor` to it

**Comment by AveCard1nal** [comment]
Guild#retrieveMember has worked.
Thank you!
