### ISSUE TITLE
Modify Bot's Browser or Device

### ISSUE THREAD

**Issue by ModEverything** [discord-jda/JDA#2645]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://github.com/discord-jda/JDA/releases/latest)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Currently the browser and device for JDA is a static string with "JDA". Could a feature be added where you could modify the browser or device in the classes `JDABuilder` or `WebSocketFactory`?

```
protected void sendIdentify()
    {
        LOG.debug("Sending Identify-packet...");
        PresenceImpl presenceObj = (PresenceImpl) api.getPresence();
        DataObject connectionProperties = DataObject.empty()
            .put("os", System.getProperty("os.name"))
            .put("browser", "JDA")
            .put("device", "JDA");
           ...}
 ```     

I think there could be a `WebSocketDevice` class, which has these values as default in the constructor. Then you could add some get/set methods for the browser or the device. Then one could customize the name of the browser and device to do things like display a mobile status by inserting "Discord iOS".

I have used JDA for a long time and really enjoy it. I can't wait for this to be a feature in the near future!

### Example Use-Case

```java
public static void main(String[] args) {
		// TODO Auto-generated method stub
		JDABuilder workshop = JDABuilder.createDefault(TOKEN, GatewayIntent.getIntents(3276799));
		workshop.setActivity(Activity.customStatus("Look! I'm on mobile!"));
		workshop.addEventListeners(new CommandManager());
                workshop.setWebsocketFactory(new WebSocketFactory().setWebSocketDevice(new WebSocketDevice().setBrowser("Discord iOS")));
		workshop.build();
	}
```

**Comment by MinnDevelopment** [comment]
We follow the API requirements. Changing this is not an official feature.

**Comment by svkkk** [comment]
unsubscribe Dnia 08 kwietnia 2024 11:56 Florian Spieß ***@***.***&gt; napisał(a):   Closed  github.com #2645  as not planned.  —  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  You are receiving this because you are subscribed to this thread. Message ID:  &lt;discord-jda/JDA/issue/2645/issue_event/12390138822 @ github . com&gt;
