### ISSUE TITLE
Commands.slash name on russian

### ISSUE THREAD

**Issue by Spilya** [discord-jda/JDA#2657]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://github.com/discord-jda/JDA/releases/latest)
- [x] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Add Russian language support to the command names, like JuniperBot. Also support for spaces would be useful
![image](https://github.com/discord-jda/JDA/assets/75587299/9334f354-0f48-4e06-84ab-2f6d8e6551f9)

### Example Use-Case

```java
Commands.slash("запрос аров", "Вы можите сформировать запрос для получения аров")
```

**Comment by Andre601** [comment]
Slash command names from what I know cannot have spaces and need to use alphanummeric characters.

What you see in the UI are two features available tho:

- [Subcommands](https://docs.jda.wiki/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.html#addSubcommands(java.util.Collection)) (The "command with space")
- [Localization](https://docs.jda.wiki/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.html#setNameLocalization(net.dv8tion.jda.api.interactions.DiscordLocale,java.lang.String))

**Comment by freya022** [comment]
Slash commands do support cyrillic characters, no need for localization
