### ISSUE TITLE
onUserActivityStart doesn't detect activity

### ISSUE THREAD

**Issue by AdamJD01** [discord-jda/JDA#2723]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked for PRs that might already address this issue.

### Version of JDA

5.1.0

### Expected Behaviour

I want onUserActivityStart to detect when a user is doing an activity (listening, playing, streaming etc) but it does nothing when my activity status gets updated for testing and doesn't even log a test message. My bot has the privileged intents enabled in the developer portal and the bot has the required permissions set in the server. I have everything enabled in the code just for testing.  I've also tested other listeners such as onUserTyping as a sanity check and the other listeners work.

### Code Example for Reproduction Steps

```java
public class UserActivityListener extends ListenerAdapter
{
    @Override
    public void onUserActivityStart(@NotNull UserActivityStartEvent event)
    {
        super.onUserActivityStart(event);

        System.out.println("Test");
    }
}
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createDefault(Token.token)
  .enableIntents(EnumSet.allOf(GatewayIntent.class))
  .enableCache(EnumSet.allOf(CacheFlag.class))
  .setMemberCachePolicy(MemberCachePolicy.ALL)
  .setChunkingFilter(ChunkingFilter.ALL)
  .setAutoReconnect(true);

JDA api = builder.build();
api.addEventListener(new UserActivityListener());
```

### Exception or Error

```yesyes
N/A
```

**Comment by AdamJD01** [comment]
Yes to all those questions. Setting a custom status works but if I for example play a game that Discord recognizes and says I'm playing then it does nothing.

**Comment by MinnDevelopment** [comment]
Can you check your privacy settings, whether you actually share your activity with others?

User Settings:

![image](https://github.com/user-attachments/assets/1e065a0a-46f4-48c6-812e-2b97cc5dcfb8)

Per-Guild Settings:

![image](https://github.com/user-attachments/assets/63461503-65e3-4214-b329-a983ca14dda0)


![image](https://github.com/user-attachments/assets/8134ab78-b143-442c-be7b-1571e210237d)

**Comment by AdamJD01** [comment]
That was the issue... I had the share your activity status by default setting disabled. Thank you for your help. I feel rather dumb now lol
