### ISSUE TITLE
Event for when Member Timeout end

### ISSUE THREAD

**Issue by BearlessDev** [discord-jda/JDA#2784]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://github.com/discord-jda/JDA/releases/latest)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

We should have an event like **GuildMemberTimeoutEnd** and **GuildMemberTimeoutStart** to do thinks when a Member get Timeout to start or end it would be cool.

*Sorry for my English im French.*

### Example Use-Case

```java
@Override
    public void onGuildMemberTimeOutEnd(GuildMemberTimeOutEndEvent e){
        Member member = e.getMember();
        Role timeOutRole = e.getGuild().getRoleById("0000");
        
        e.getGuild().removeRoleFromMember(member, timeOutRole).queue;
    }
```

**Comment by freya022** [comment]
JDA does not have such an event simply because Discord doesn't provide one, as the timeout end timestamp doesn't change until another timeout is issued.

**Comment by BearlessDev** [comment]
Ohh okay thanks for the answer !
